---
title: "High model uncertainty and niche underfilling in the invasive range of the annual grass _Avena barbata_ using Gaussian processes (Working title - we need a better title)"
author: "Kate Crosby, Nick Golding, & Robert G. Latta"
date: "November 15, 2014"
output: html_document
---
## Abstract

Assessing whether a niche shift has occurred during a biological invasion is important for understanding evolutionary dynamics, as different environments are thought to exert different selective pressures. Climatic niche shifts are generally thought to be rare among invaders. Using a recently developed Gaussian process species distribution model we investigated niche shifts and niche overlap in _Avena barbata_, an annual, invasive grass that has colonized all five Mediterranean climate regions. We constrained our investigation to two of these regions: the state California (where it is invasive), and the Iberian Peninsula (where Californian populations are thought to have originated). Occurrence data was obtained from the Global Biodiversity Information Facility (GBIF) as well as from a survey of California in 2010. We examined between 12 climatic variables and one edaphic variable in modeling the niche of _A. barbata_ using three different spatial sampling schemes to account for spatial bias in reporting of occurrence records. Separate models were trained on subsets of data in both ranges and then used to predict probability of presence in the other range and to identify environmental variables that were important in predicting presence. We applied a two-factor MANOVA and linear discriminant functions to assess niche shifts and niche overlap in _A. barbata_ populations. Models predicting to the opposite range were subject a large amount of uncertainty. MANOVA showed significant difference between the means of environmental variables in both ranges predicting presence and absence, and linear discriminant functions showed little overlap between geographic ranges. We interpreted this as evidence of a possible niche shift between Iberia and California, which may suggest that _A. barbata_ is undergoing evolutionary change.

## Introduction

The frequency of occurrence of climatic niche shifts during or throughout biological invasions is unclear. At least one review proposes that niche shifts are the exception as opposed to the rule (Guisan et al., 2014). Climatic niche overlap and conservatism may emerge as the most persistent findings because characterizations of the home and invaded niches focus mainly on climatic factors (precipitation and temperature). Generally, there can be fair amount of climatic overlap for different geographic regions, and particularly Mediterranean climates (Ackerly, 2009), and even more expansive geographic regions. For example, a meta-analysis of 50 Holarctic terrestrial invasive plants found that 80% of these have substantial niche overlap and thus niche stability when compared to their home range (Petitpierre et al., 2012; Guisan et al., 2014). Niche conservatism or niche stability occurs when a species in one geographic region moves (sometimes thousands of kilometers) to another geographic region, but continues to occupy the same niche or environmental conditions as it did in its geographic place of origin, in contrast, a complete niche shift is when a species either occupies the same or different geographic space, but shifts its environment or its niche (Guisan et al., 2014). 

The main objective of species distribution models (SDMs) is the prediction of presence and absence of one or many species given a set of environmental conditions.  In doing so, these models characterize - however imperfectly - the niche (Hutchinson, 1959). SDMs have been used to highlight niche changes or overlaps in species distributions/niches at different stages of colonization or invasion of new ranges (Václavík & Meentemeyer, 2011), predict new potential niches with respect to climate change (Pearman et al., 2008), and errors produced from SDMs may be informative as to whether the species has evolved or undergone a niche shift (Fitzpatrick et al., 2007).

Ecological studies using SDMs in the study of invasions or range expansions, may come to a crossroads with evolution, and either directly or indirectly address the question of local adaptation to a new niche, in that the invaders would experience low fitness back in their home range (Godsoe et al., 2009; Yoder et al., 2014). The process of local adaptation and divergent selection would inherently imply a species has undergone a niche shift, where certain genotypes of a species have higher or lower fitness in different environments. Niche shifts do not necessarily indicate adaptation, as a species may have always possessed the genetic resources or plasticity for a particular trait such as flowering time (Levin, 2009), but merely not had the opportunity for transplant to a new niche. There may also be eco-evolutionary dynamics, where release from ecological competitors (release from selection) affects the amount of genetic variation available in the population for future generations (Emery & Ackerly, 2014).
 
Invasive populations often suffer founder effects and the loss of adaptive (as opposed to neutral) genetic variation due to genetic bottlenecks relative to native populations. As such an invasion could result in four possibilities with respect to niche occupancy. First, the newly invaded niche may be home to a subset of genetic variation (niche contraction) that exists in the home range. Second, the newly invaded niche may be broader than the old niche (niche expansion). Third, there could also be some limited overlap between niches, but a niche shift occurs in the new habitat. Finally, there is also the possibility that there has been no niche shift, as environmental variables in either region show strong overlap with each other. 
_Avena barbata_ Pott ex Link is an annual grass that is invasive to California, and highly selfing. Following colonization in California, it was observed that there were few sets of monomorphic allozyme genotypes present and few recombinants (Clegg & Allard, 1972; Allard et al., 1972; Hamrick & Allard, 1975). It was further demonstrated that these allozyme genotypes were composed of a reduced subset of alleles of those found in Iberia – their suspected place of origin (Garcia et al., 1989). These observations suggest that introduced populations of _A. barbata_ to California experienced a bottleneck and lost genetic variation during colonization. Further, it was observed that _A. barbata_ individuals in California occupy populous annual stands unlike the small patches of ruderal stands it forms in its Iberian home range (Jackson, 1985), which may be indicative of a niche shift.
If adaptive genetic variation were lost during a or repeated bottleneck(s), then this leads to the prediction that individuals are restricted in occupying the full breadth of the niche occupied by their Spanish ancestors, i.e. SDMs trained in Iberia would over-predict the niche in California. But if, on the other hand, multiple introductions have occurred in California (Crosby et al. 2014), and these introductions have recombined (Ch.4) – the resultant new combinations might allow for niche overlap with Iberia, and possibly a niche shift if the invaders have evolved since being introduced to California. If this were the scenario, than models trained in Iberia would under-predict the niche. 
In our study we sought to characterize the amount of niche overlap and niche shifts between invasive populations of _A. barbata_ and native Iberian populations, in doing so, we also characterize the niche in both ranges. We apply a new method of SDM, using Gaussian processes (GPs) (Golding, 2013), which is one of the only methods that deals well with “presence-only” data. We sought to characterize the niche in Spain, using a GP model, and then predict the probability of presence in California using this model. We then repeated the process of modeling the niche in California and used this model to predict the probability of presence in Iberia. 


## Methods

#### _Occurrence data: native range and invasive range_
_A. barbata_ populations are found on six continents with the exception being Antarctica, and show a preference for characteristic Mediterranean biomes. The Mediterranean Basin is thought to be its native range, but this may also extend well into the Middle East (Baum 1977). It has invaded Mediterranean biomes in Australia, North America (California), South America, and South Africa. As we were mostly interested in evaluating potential niche shifts and niche conservatism of _A. barbata_ populations in California, we chose to define the “native range” as the Iberian Peninsula plus Northern Morocco, and the “invasive range” as the state of California. The Iberian Peninsula and Northern Morocco are thought to be the source of present day Californian populations, with initial colonization occurring in California during the Spanish missionary period on the Western side of the Americas (Garcia et al., 1989; Minnich, 2008). Additionally, both these regions were intensively surveyed, over almost the same period (1800s-2000s) most other regions were inconsistently or sparsely sampled. The only other region with comparatively intense sampling was the continent of Australia with over 3000 records of occurrences; we plan on revisiting this dataset at a later date.

Total _A. barbata_ occurrence data was obtained from several sources: the public data portal for the Global Biodiversity Information Facility (GBIF) using the r-package ‘rgbif’ v. 0-5 (Chamberlain et al., 2014), the National Small Grains collection at the USDA, the California Consortium Herbaria, and our lab’s own geographic survey  (see Chapter Four) of the state of California in 2010. The total number of records of occurrences from this initial global search was 14554, with occurrence dates ranging from the early 1800s – 2014 in all environments. We screened the data as GBIF interfaces regularly with many databases and data portals, and this interfacing can result in duplicate records.  we purged duplicates by keeping only one record for each unique pair of GPS coordinates. We also ensured that remaining occurrences were georeferenced, correctly – i.e. were in the correct country, and not in the ocean, by spatial query using the R-package ‘raster’, and by eye. The total number of occurrences for native and invasive ranges was 3916 with 998 occurrences in the invaded range, and 2908 in the native range.

#### _Sampling bias and the generation of background (aka ‘pseudo-absence’) data_
There are two main problems that can occur with SDMs sampling bias and the lack of “true” absence data in occurrence datasets. Sampling bias occurs because of over-sampling regions close to populated urban areas, roadways, and other easily accessible areas such as parks, and may create spurious associations between environment and occurrences when attempting to improve the predictability of an SDM. Sampling bias may also occur because a concentrated sampling effort has taken place due to various environmental, provincial, county, or region-wide biodiversity assessment programs. 

To deal with sampling bias, Philips et al. (2009) suggest using a species that co-occurs with the species of interest, but may occupy a slightly shifted different distribution. We found this suggestion to be cumbersome to fulfill in California, given that _A. barbata_ is invasive there and does not co-occur with a related species throughout both its ranges. Instead, we used three approaches to account for sampling bias. First, we subsampled both Iberia and California by overlaying a raster grid of varying sizes (20, 15, 10, 5-kms 2) across the entire range and chose one individual in each grid square.
<!-- This citation might be useful here:
	1. Boria, R. a., Olson, L. E., Goodman, S. M. & Anderson, R. P. Spatial filtering to reduce sampling bias can improve the performance of ecological niche models. Ecol. Modell. 275, 73–77 (2014). -->
By eye, we judged which of these grid sizes appeared to prune the data sufficiently in areas with many occurrences, but without reducing the total number of occurrences throughout the range. In both cases, a raster grid of 15-km2 was chosen as a grid size. Second, we targeted our sub-sampling on only those regions in each range that may have been repeatedly sampled due to their proximity to populated areas or political boundaries. We overlaid a 15-km2 raster grid over each partial range, and chose only one individual within each grid cell. Finally, because the data were obtained mostly from databases, we could not be certain as to whether these areas were sampled in a biased way or whether these represented actual densely occupied habitats. Thus, SDMs were also performed on datasets without systematically eliminating any of the occurrence data.

SDMs produce more accurate results if absence data recorded from a formal geographic survey is used, and unfortunately, no (Iberia) and/or little (California) were available for _A. barbata_. An alternative to using actual absence data to improve SDM accuracy is to include a large number of user-generated pseudo-absences (Barbet-Massin et al., 2012). We generated “pseudo-absences” as background data across each of the ranges. We generated an equal number of “absences” as there were “presences”, and these were generated randomly across the range, in the following way: for each occurrence point, we drew a circle with a radius of 50-km2 (or 4km) and one random point within this circle was designated an “absence”. 

#### _SDM technique: GRaF_
We modelled the influence of environmental variables on the spatial distribution of _A. barbata_ in each region using a Gaussian process (GP) SDM fitted using the R package ‘GRaF’ v. 0.1-12 (Golding, 2013).
GPs have recently been proposed for use in SDM (Vanahatalo _et al._, 2010) and GP SDMs fitted by numerical approximation have been shown to have strong predictive power and be computationally feasible for SDM analyses (Golding & Purse, submitted).
As well as their strong predictive power, GP SDMs have a number of benefits over other commonly used approaches, including robust estimation of prediction uncertainty, inbuilt prevention of model overfitting and methods for accounting for uncertainty in input data.
As GP SDMs are not familiar to most ecologists, we provide a brief description of the approach here but refer the interested reader to Golding & Purse (submitted) for a an ecological introduction or to Rasmussen & Williams (2006) for a more detailed overview of GPs from a machine-learning perspective.

As with all SDMs, GP SDMs consider the probability of presence of the species to be explained by some unknown, underlying function of a set of environmental variables (which may be interpretted as the species' fundamental niche) and attempt to construct a quantitative model of this function.
In the GP SDM, this underlying function is modelled as a stochastic process derived from a correlated multivariate normal distribution.
The value of this process at a given site (the probability of species presence) is assumed to be more correlated with environmentally similar sites, than with dissimilar sites.
The manner in which correlations decay with environmental distance, is modelled using a covariance function and both this function and the `shape' of the process are learnt from the data.
Bayesian inference is then carried out to infer the most likely underlying model of the species' fundamental niche.

The importance of each environmental covariate is quantified by a set of `lengthscale' parameters, determining their relative influence on the species' distribution' (with smaller lengthscales indicating a stronger influence).
The number of degrees of freedom is not clearly defined for a stochastic Bayesian model such as this, preventing the use of common model comparison criteria.
Instead, the overall complexity and goodness of fit of a fitted GP SDM can be quantified by the number of effective parameters (pD, larger values indicating a more complex model) and Deviance Information Criterion (DIC) (Spiegelhalter _et al._, 2002).
Like other information criterion, the DIC estimates the compromise between model fit and model complexity, with lower indicating a more parsimonious model fit.

#### _Initial selection of environmental variables_
Another important consideration in generating an SDM with high predictive ability is choosing a representative suite of environmental variables thought to represent the niche of the species of interest. We used a combination of historical observations, literature specific to _A. barbata_ (Pinero, 1982) and annual plants (Jackson, 1985), and past observations over four field seasons in California (Latta, pers. comm). While these choices are subjective to a certain degree, we chose variables based on reported life-history traits of _A. barbata_, climate data, and edaphic (soil) traits of each region. For each class of environmental variable we aimed to choose variables that would be relatively consistent for the time period of when the occurrences were recorded 1800s – present, so we could compare the initial colonization period in California (Blumler, 2000; Minnich, 2008), up to present day. 

Because _A. barbata_ is a winter annual plant, the following observations were used to select an appropriate suite of climatic variables: Nov-Feb precipitation in each region is thought to aid in initial sprouting and growth, along with warmer winter temperatures, a warm wet spring in March-April for initial growth and flowering, and indirectly, a hot, dry, summer is thought to aid in eliminating other vegetation that might otherwise compete with _A. barbata_ for resources. Raster grids for mean monthly precipitation and temperature were obtained from the WorldClim database v. 1.4 at a resolution of approximately 1km at the equator or 30 arc seconds. In addition to these climate variables, we also obtained raster grids for mean monthly actual evapotranspiration (AET) and mean monthly potential evapotranspiration (PET) as the difference between AET and PET (i.e. water deficit) are relevant to plant survival.

Soil type as assessed by various classification systems (e.g. USDA and World Reference Base for soil types) may not adequately capture similarities between regions, instead emphasizing categorical differences. As our goal was to be able to compare native and invasive regions, we included one continuous variable, soil pH in a 1 X 1 km grid, which has been shown to greatly improve the predictability of plant SDMs (Dubuis et al., 2012), and is measured using the same method in both locations. Oats and other annual grasses are known to prefer slightly acidic soils, but can exist within a broad range of pH values ~ 3.5-7.

In total, this initial selection left us with thirty-three environmental variables (Table 3.1) to consider for further niche evaluation. All raster grids containing environmental data were clipped to the extent of the range of occurrences in both California and Iberia. 


#### _Final selection of environmental variables_
To reduce the amount of complexity in explaining and interpreting the niche of _A. barbata_ in its home range we sought to choose fewer variables that might best explain the niche of _A. barbata_. We examined the degree to which environmental variables were correlated to each other in the Iberian Peninsula and in California. To estimate the degree of correlation between variables, we used Spearman’s correlation coefficient at cut-off values of: >|0.99|, >|0.98|, >|0.95|, and >|0.90|, removing one of the correlated variables from the dataset. In Iberia, this reduced the number from variables to thirty-three, twenty-five, twelve, and six, respectively. In California, this reduced the number variables from twenty-eight, twenty-one, eleven, and five, respectively. We iteratively fit GRaF models 100 times to different random samples of 30% of our occurrence data with each different set of variables. In each case, the optimal lengthscale option (as specified above) was turned on, and flat priors were used.

The DIC, pD, and the remaining 70% of presence/pseudo-absences that were correctly classified were used to choose the optimal number of environmental variables. In order to construct the most general, parsimonious niche models in each region we sought to minimize pD, while also maintaining a low DIC. To calculate the proportion of correctly classified presences and pseudo-absences predicted using a GRaF model, we set a posterior threshold estimate of 0.5. Any posterior estimate of 0.5 was classified as present, and any estimate below 0.5 was classified as an absence. These classifications were then compared to the actual records of presences and <!--pseudo-?  -->absences to calculate proportion of records that were correctly classified with the GRaF model.

#### _Model prediction and prediction diagnostics_
For each of the sampling scenarios each trained Iberian GRaF model was used to predict the remaning (70%) of the records in Iberia, and then all records in California. We then took the California-trained model and predicted the remaining occurrences in California, and then all of Iberia. The strength of each trained GRaF model was evaluated using three criteria: the area under (AUC) the receiver operating curve (ROC), number of occurrences and absences that were correctly classified, and mean model uncertainty. AUC values scale from 0 to 1 and evaluate a model’s ability to correctly classify occurrence records; an AUC value of 1 indicates that the model correctly classifies all records of occurrence, a value of 0.5 is the same as random chance, AUC values < 0.5 perform worse than random chance. But, AUC has faced criticism in the past (Lobo et al., 2008), so we used number of occurrences that were correctly classified based on a threshold value that was the average between model sensitivity (true positive rate) and specificity (false positive rate). Mean model uncertainty was also calculated by subtracting each of the upper 95% credible intervals from the lower 95% credible intervals for each posterior estimate of probability of presence or absence. 

#### _Niche comparison_
For ease of interpretation with respect to niche comparison and overlap, we narrowed our comparison by focusing on the two variables with the shortest lengthscales (those variables in a GP model that are driving the relationship between probability of presence and the niche) from each of the training models in both ranges, i.e. four environmental variables in total. These variables were then used for a coarse comparison using a two-factor multivariate analysis of variance (MANOVA) for the factors of occurrence and geographic area, i.e. presence vs. absence and Iberia vs. California. We performed MANOVAs for each of the three spatial sampling schemes. In order assess the amount of niche overlap with respect to these two factors we performed linear discriminant analysis (LDA) for each of the spatial sampling schemes, and also on the complete dataset with all thirty-three environmental variables included for the purpose of niche comparison. 

## Results

#### _Sub-selection of environmental variables_
For the initial GRaF analysis where we selected a subset of the original thirty-three environmental variables, all one-way ANOVAs were significantly different for each of the three parameters evaluated for choosing the optimal number of environmental variables (Fig. 3.1 & 3.2). 

For both Iberia and California, the comparison of means using Tukey’s post-hoc tests revealed that all means for the pD and the number of records correctly classified were significantly different from each other. In Iberia, the mean DIC differed for only the level of six environmental variables; the other levels did not differ from one another (Fig. 3.1). In California, the pairwise mean DIC differed for only the level of five variables (Fig. 3.2). To minimize model complexity (lower pD), but also maintain a good model fit (lower DIC) we chose twelve environmental variables to characterize the home range niche of _A. barbata_; in California, we chose to use eleven variables. 

In Iberia, twelve variables correctly classified presences/absences on average 65.6%, a 3% improvement from six variables that classified 62.6%, while models using all thirty-three variables improved the classification by only 2.8%, mean 68.4% (Figs. 3.1 & 3.3-3.5). The chosen twelve environmental variables were: mean actual evapotranspiration (AET) for the months of November, December, May, and July; mean potential evapotranspiration (PET) for March, May, and July; mean temperature for the months of May and July; mean precipitation for the months of February and March; and soil pH (Figs. 3.3-3.5). In general, these variables were thought to be a suitable subset of uncorrelated descriptors of the Iberian Mediterranean environment. There was much more uncertainty around probability of presence posterior estimates in relation to environmental variables for the 15 km2 raster dataset (Fig. 3.4), than there was for the datasets with more occurrence data included (Fig. 3.3 & 3.5). The only common environmental variable with a short lengthscale between any of the spatial datasets was average warm May temperature between 10-15°C (Figs. 3.4 & 3.5).

In California, the eleven variables correctly classified records on average 68.5 %, a 4.7% improvement from five variables that correctly classified on average 63.8% of records, while models using twenty-eight variables improved the classification by only 2.6%, mean 71.1% (Figs. 3.2 & 3.6-3.8). For California, the chosen eleven environmental variables used were: actual evapotranspiration (AET) for the month of January; potential evapotranspiration (PET) for January, February, March, April, and July; mean temperature for the months of December, April, and July; mean precipitation for March; and soil pH (Figs. 3.6-3.8). As in Iberia, there was much more uncertainty with the 15 km2 raster dataset (Fig. 3.7) relative to the two other spatial datasets (Figs. 3.6 & 3.8), which contained more occurrence data. Mean December temperature had a short lengthscale (high predictive power) in all three Californian occurrence datasets, and predicted a reasonably high probability of presence between mean temperature of 5-10°C (Figs. 3.6-3.8). 

GRaF models in both regions had four variables in common: mean monthly AET for November, mean monthly PET for March, mean July temperature, and soil pH (Figs. 3.3-3.8). High probability of presence occurred in both ranges for average July temperatures of ~ 25°C, and for slightly acidic soils ~ 5-5.5 pH (Figs. 3.3-3.8). However when examining the full dataset lengthscale plots, mean monthly PET in March was slightly higher for California than Iberia, as was mean monthly AET in November (Figs. 3.5 & 3.8). This suggests that _A. barbata_ occurs in moister environments in California than it does in Iberia. 

#### _Testing model performance_
The Iberian trained models were more complex than its Californian counterpart (Table 3.2) having a higher number of effective parameters (pD) in the model, and a higher DIC as a result. As expected, for all three spatial sampling schemes, the Iberian trained model correctly classified more occurrence data in Iberia than California, had a higher AUC in Iberia than in California, and had much lower mean model uncertainty in Iberia than in California (Table 3.3). Prediction maps generated using datasets with fewer occurrence records had higher uncertainty (grey points in Figs. 3.9 & 3.10) than datasets where all occurrence data was included. However, when all occurrence data was included in the models, most of the true presence predictions from the Iberian trained model were centered on heavily populated areas in both Iberia and California (Fig. 3.11). 

The Californian trained model had a lower number of effective parameters (pD) in the model, and a lower DIC than the Iberian model. It correctly classified more occurrence data in California than Iberia for all three spatial sampling schemes. However, the Californian trained model performed better at predicting occurrences in Iberia the than the Iberian model performed in predicting presences in California (Table 3.3).


#### _Niche comparison_
Results of the two-factor MANOVA for all three spatial sampling schemes point to significant differences in the multivariate means between geographic areas, presences and absences, and the interaction between those two single factors. The factor that displayed the most variance between groups was geographic area (Table 3.4) for all three spatial sampling schemes. For every sampling scheme, and all of the data as well, ordinal plots of the first two-discriminant axes analyses revealed separation between geographic areas on the first axis (Fig. 3.12). This separation along the first discriminant axis decreased as fewer records were examined with respect to each of the most important environmental variables, with the spatial data set of one record per 15 km2 showing the most amount of overlap (Fig. 3.12). The overlap as the amount of records decreases is perhaps a function of model uncertainty; with fewer records the 15-km2 dataset had the higher uncertainty and less resolution in correctly classifying presences vs. absences (Table 3.3). There was separation between presences and absences in the Californian along the second axis for most spatial categories examined (Fig. 3.12), but substantial overlap for Iberian presences and absences, suggesting that Iberian pseudo-absences occur in the same environments as Iberian presences.

## Discussion
In her general study of ecological origins of Mediterranean grasses in California, Jackson (1985) notes that most annual grasses in their native Mediterranean Basin form small, disjunct communities, not the dense annual stands they do in California. This is potentially indicative of either a climatic niche shift or the release from natural enemies of the introduced Mediterranean Basin grasses to California. _Avena barbata_ occurs in all five Mediterranean climate regions, which are characterized by warm winters with substantial rainfall occurring until early spring, and hot, dry summers (Jackson, 1985). In looking at environmental variables of these two climate regions, the Mediterranean Basin (focusing on Iberia), and California, we attempted to characterize niche overlaps and/or niche shifts in _A. barbata_ occurrence using a new type of SDM – GP (Golding, 2013), which incorporates uncertainty in predictively modeling species occurrences. 

Models trained in both ranges had three common climatic variables (mean AET Nov., mean PET March, mean temperature July), and one edaphic variable (soil pH) shared between them, and this demonstrates that there is some niche similarity between the ranges. High average July temperatures predicted a high probability of presence in the ranges, but average PET in March and AET in November was noticeably different for the ranges with a higher average PET in March and AET in November in California predicting a high probability of presence compared to Spain. However, the environmental variables with the shortest lengthscales in each of the models were generally different between the ranges, and lengthscale parameters and model complexity were sensitive to the spatial dataset under consideration. 

As expected, in every case, each of the models trained in their own range performed better at predicting occurrences in their own range than they did in the opposite range. In general, Iberian trained models across all three spatial sampling scenarios poorly predicted Californian occurrences. Californian trained models did better at predicting presence in Iberia, but there was also a high degree of uncertainty associated with these predictions. We suggest that the high uncertainty associated with each of the trained models attempting to predict the opposite range suggests that the relative importance of certain environmental variables differs between both geographic ranges and points to a climatic niche shift. The MANOVA and linear discriminant function analysis of the most important lengthscales in GRaF models are also suggestive of niche dissimilarity. However, as spatial datasets were pruned down to a fewer number of occurrences, this separation lessened.

SDMs are very much dependent on both accurate occurrence and environmental data, and the spatial and timescales at which environmental data are collected. In general, these data were interpolated at a high resolution for a raster dataset (~1km at the equator), but the number of observation stations does differ between Iberia and California, with California having more observation stations than Iberia (Hijmans et al., 2005). 

An additional consideration is that these raster datasets are not necessarily “high-resolution” for an annual plant, which may prefer specific microclimates that cannot be captured with the current scale of environmental data. Recently, it has been suggested that in order to accurately describe the macroclimate of a species, substantial measurement and characterization of the microclimate must occur first to inform large geographic scale SDMs (Gillingham et al., 2012; Harwood et al., 2014).  Our study was limited to the macroclimate, due to time and the spatial spread of occurrences in both these ranges. 

This study also mainly considered climatic variables (with the exception of soil pH) in attempting to describe the niche of _A. barbata_. As important as climatic variables can be in describing the niche of a species, these variables might serve better to inform the range limits of the species as opposed to the distribution within each range. It is also probably important to consider other biotic variables, such as mutualistic or symbiotic relationships with other species (Godsoe et al., 2009). In the case of invasions, the release from ecological competitors (‘the enemy-release hypothesis’) in the new range may be an additional factor in predicting probability of presence (Colautti et al., 2004; Emery & Ackerly, 2014). We did not make an attempt to include biotic variables in the present study, as doing so in both geographic ranges would have proven a difficult task (not to diminish their potential importance in predicting _A. barbata_ occurrences). Another potential factor that may have played a role in determining the distribution of _A. barbata_ in the invasive range are fire cycles, where an invasive grass provides ample fuel for fires, which then increase in frequency destroying the native vegetation (reviewed in D’Antonio and Vitousek 1992).

Sampling effort recording presence and absence can also heavily bias which environmental variables are most important in predicting presence (Phillips et al., 2009), and to some extent this difference is observed between the three spatial sampling schemes used here. By selectively altering the number of occurrences by targeting only one individual in densely sampled areas based on a reasonable raster grid size or pruning the data across the total range, the relative importance of environmental variables changes in the GP model. The one exception to this observation is a warm average mean temperature in December in California, suggesting that warm winters in California are associated with a high probability of presence for _A. barbata_. By pruning the dataset, the average uncertainty in each model shifts dramatically as well, with the sparser the dataset (in terms of number of occurrences) the greater the uncertainty in model predicitions.

When all evidence is considered, we think it is possible that _A. barbata_ occupies a different climatic niche in California than it does in Iberia, and may preferentially occupies different environments than those it occupies in Iberia. First, subsets of different environmental variables were better at optimally predicting a high probability of presence in models trained in both ranges. This on its own may not necessarily indicate a shift because there could be substantial seasonal offsets between the two ranges, for example the rainiest month in Iberia may be November, and the rainiest month in California may be Dec. However, two of the variables shared between models trained in both ranges had different means – these were mean March PET and November AET. This is the first time (to our knowledge) GP has been used to investigate niche shifts. We would tend to advance that high uncertainty associated with models predicting to the opposite range means that the subset variables that predicts presence in Iberia (for example) does not reliably predict presence in California. No matter the spatial category, there was always a fair amount of uncertainty with models predicting occurrence in the opposite range. Finally, both the two-way MANOVA and LDA seem to show that when the most important environmental variables are considered, there is little overlap between them when considered as multivariate wholes. 

We note that this potential climatic niche shift is not indicative of evolutionary change or local adaptation in either range. In the present study, it cannot be ruled out that colonizing _A. barbata_ individuals may have had substantial physiological and also phenotypic plasticity available to changing stresses like moisture gradients, which may have then lead to altering a trait such as flowering time (Sherrard et al., 2009). If evolutionary change were occurring in California, we hypothesize it is because of other factors such as recombination (Chapter 4) possibly between the three maternal introductions (Crosby et al. 2014) from different parts of the native range. 




<!-- Citations:
1. Vanhatalo, J., Veneranta, L. & Hudd, R. Species distribution modeling with Gaussian processes: A case study with the youngest stages of sea spawning whitefish (Coregonus lavaretus L. s.l.) larvae. Ecol. Modell. 228, 49–58 (2012).

1. Rasmussen, C. & Willians, C. Gaussian processes for machine learning. (MIT Press, 2006). at <http://www.ncbi.nlm.nih.gov/pubmed/15112367>

1. Spiegelhalter, D. J., Best, N. G., Carlin, B. P. & van der Linde, A. Bayesian measures of model complexity and fit. J. R. Stat. Soc. Ser. B (Statistical Methodol. 64, 583–639 (2002).
 -->



